sudo: required
language: python
cache: pip

services:
  - docker

python:
  - "3.6"

env:
  - EXERCISES_DOCKER=1
  - EXERCISES_GRPC_MY_CLIENT=1
  - EXERCISES_GRPC_MY_SERVER=1
  - HELLO_COMPOSE=1
  - HELLO_GRPC=1
  - HELLO_GRPC_TYPED=1
  - WEATHER_APP=1

before_install:
  - sudo apt-get update -y && sudo apt-get install -y curl
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

install:
  - pip install mypy grpcio-tools grpcio mypy-protobuf

script:
  # Run exercises
  - if [ "$EXERCISES_DOCKER" == 1 ]; then sh -c "cd exercises/docker/run_docker && pip3 install -r requirements.txt && python3 main.py"; fi
  - if [ "$EXERCISES_GRPC_MY_CLIENT" == 1 ]; then sh -c "cd exercises/grpc/my_client && make serverd && make client"; fi
  - if [ "$EXERCISES_GRPC_MY_SERVER" == 1 ]; then sh -c "cd exercises/grpc/my_client && make protos"; fi

  # Run examples
  - if [ "$HELLO_COMPOSE" == 1 ]; then sh -c "cd hello_compose && docker-compose up --build -d && docker wait hello_compose_foo_1 && docker-compose logs foo"; fi
  - if [ "$HELLO_GRPC" == 1 ]; then sh -c "cd hello_grpc && make serverd && make client"; fi
  - if [ "$HELLO_GRPC_TYPED" == 1 ]; then sh -c "cd hello_grpc && make serverd && make client"; fi

  - if [ "$WEATHER_APP" == 1 ]; then cd weather_app && make config && docker-compose up --build -d && docker wait weather_app_client_1 && docker-compose logs client; fi
