sudo: required
language: python
cache: pip

services:
  - docker

python:
  - "3.6"

env:
  - EXERCISES_DOCKER=1
  - EXERCISES_GRPC_MY_CLIENT=1
  - EXERCISES_GRPC_MY_SERVER=1
  - HELLO_COMPOSE=1
  - HELLO_GRPC=1
  - HELLO_GRPC_TYPED=1
  - WEATHER_APP=1

before_install:
  - sudo apt-get update -y && sudo apt-get install -y curl
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

install:
  - pip install mypy grpcio-tools grpcio mypy-protobuf

script:
  # Run exercises
  - if [ $EXERCISES_DOCKER == 1 ]; then cd exercises/docker/run_docker && docker image build -t run_docker:latest . && docker run --rm run_docker:latest; fi
  - if [ $EXERCISES_GRPC_MY_CLIENT == 1 ]; then cd exercises/grpc/my_client && make server & && wait=$(make client); fi
  - if [ $EXERCISES_GRPC_MY_SERVER == 1 ]; then cd exercises/grpc/my_client && make protos; fi

  # Run examples
  - if [ $HELLO_COMPOSE == 1 ]; then cd hello_compose && docker-compose up --build & && docker-compose wait foo; fi
  - if [ $HELLO_GRPC == 1 ]; then cd hello_grpc && make server & && wait=$(make client); fi
  - if [ $HELLO_GRPC_TYPED == 1 ]; then cd hello_grpc && make server & && wait=$(make client); fi

  - if [ $WEATHER_APP == 1 ]; then cd weather_app && make test; fi
